import type { NavigationConfig } from '@/types'

export const fallbackNavigation: NavigationConfig = {
  version: '1.0.0',
  generatedAt: new Date().toISOString(),
  defaultRouteByRole: {
    admin: '/dashboard',
    teacher: '/dashboard',
    student: '/booking',
    ziggy: '/dashboard',
  },
  featureFlags: {
    bookingEnabled: true,
    reportsEnabled: true,
    systemEnabled: true,
    serviceToolsEnabled: false,
  },
  items: [
    {
      type: 'link',
      id: 'dashboard',
      label: 'Dashboard',
      path: '/dashboard',
      icon: 'LayoutDashboard',
      order: 1,
    },
    {
      type: 'group',
      id: 'booking-group',
      label: 'Rezerwacje',
      icon: 'Calendar',
      order: 2,
      featureFlag: 'bookingEnabled',
      children: [
        {
          type: 'link',
          id: 'booking-calendar',
          label: 'Kalendarz',
          path: '/booking',
          icon: 'CalendarDays',
          order: 1,
          rolesAllowed: ['admin', 'teacher', 'student', 'ziggy'],
        },
        {
          type: 'link',
          id: 'booking-admin',
          label: 'Zarządzanie',
          path: '/booking/admin',
          icon: 'Settings',
          order: 2,
          rolesAllowed: ['admin', 'teacher', 'ziggy'],
        },
      ],
    },
    {
      type: 'group',
      id: 'system-group',
      label: 'System',
      icon: 'Server',
      order: 3,
      featureFlag: 'systemEnabled',
      rolesAllowed: ['admin', 'ziggy'],
      children: [
        {
          type: 'link',
          id: 'system-status',
          label: 'Status',
          path: '/system/status',
          icon: 'Activity',
          order: 1,
        },
        {
          type: 'link',
          id: 'system-logs',
          label: 'Logi',
          path: '/system/logs',
          icon: 'FileText',
          order: 2,
        },
        {
          type: 'link',
          id: 'system-users',
          label: 'Użytkownicy',
          path: '/system/users',
          icon: 'Users',
          order: 3,
          permissionsRequired: ['USERS_MANAGE'],
        },
      ],
    },
    {
      type: 'link',
      id: 'health',
      label: 'Health Check',
      path: '/health',
      icon: 'HeartPulse',
      order: 100,
      rolesAllowed: ['admin', 'ziggy'],
    },
  ],
}
